In [2]:
# 1 D Array(vectors)
import numpy as np
arr=np.array([1,2,3,4,5])        #list is passed
print(arr)
print(type(arr))

# Accessing 1 D array eleemnt 
print(arr[0])

#Slicing 1D array
print(arr[:])
print(arr[1:4])
print(arr[-1:])

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
[1 2 3 4 5]
[2 3 4]
[5]


In [12]:
arr=np.array((6,7,8,9,10))        #tuple is passed
print(arr)
print(type(arr))

[ 6  7  8  9 10]
<class 'numpy.ndarray'>


In [20]:
# 0 D Array(scalars)
arr=np.array(45)
print(arr,type(arr))


45 <class 'numpy.ndarray'>


In [44]:
#2 D Array 
arr=np.array([[1,2,3],[4,5,6]])
print(arr,type(arr))

# Accessing 2D array eleemnt 
print(arr[0][1])                          # 0 row & 1 column
print(arr[0][-1])
print(arr[-1][-1])


#slicing 2 D array
print(arr[0,1:3])
print(arr[1,1:3])       
print(arr[0:2,1:3])
print(arr[:,:])

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>
2
3
6
[2 3]
[5 6]
[[2 3]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [4]:
#3 D Array
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr,type(arr))

# Accessing 3D array eleemnt 
#print(arr[0][0][0])

#Slicing 3 D array
print(arr[0:,0:1,0:1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] <class 'numpy.ndarray'>
[[[1]]

 [[5]]]


In [29]:
# To check dimnension (ndim)
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr1.ndim)
print(arr2.ndim)

2
3


In [68]:
#converting from one data type to another
arr=np.array([1,2,3,4,5])
print(arr.dtype)
arr1=np.array([1,2,3,4,5],dtype='S')
print(arr1.dtype)


#converting from one data type to other
newarr=arr.astype(float)
print(newarr)

newarr1=arr.astype(str)
print(newarr1)

int32
|S1
[1. 2. 3. 4. 5.]
['1' '2' '3' '4' '5']


In [73]:
# Copy vs View
#copy---- No changes will be reflected in original array if we make changes in new copied array
arr=np.array([2.5,3.5,4.5,5.5,6.5])
newarr=arr.copy()
print(newarr)

arr[0]=1.5
print("\n",arr)
print(newarr)


[2.5 3.5 4.5 5.5 6.5]

 [1.5 3.5 4.5 5.5 6.5]
[2.5 3.5 4.5 5.5 6.5]

 [1.5 3.5 4.5 5.5 6.5]
[  2.5 100.    4.5   5.5   6.5]


In [75]:
#view----- changes will get reflected if you make changes in original or copied array
arr=np.array([100,200,300,400])
newarr=arr.view()
print(newarr)

newarr[0]=500
print("\n",newarr)
print(arr)

[100 200 300 400]

 [500 200 300 400]
[500 200 300 400]


In [ ]:
#shape of an array-----number of elements in each dimension

In [84]:
arr1=np.array([1,2,3,4,5])
arr1.shape
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
arr2.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [93]:
# Reshaping ----changing elements or dimensions of an array
arr1=np.array([1,2,3,4,5,6])
print(arr1.reshape(2,3))

arr2=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print("\n",arr2.reshape(3,2,2))

[[1 2 3]
 [4 5 6]]

 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [105]:
#Iteration in 1D array
'''  
arr1=np.array([100,200,300,400,500,600])
for i in arr1:
    print(i)
'''
#nditer() to iterate over array
for i in np.nditer(arr1):
    print(i)

100
200
300
400
500
600


In [107]:
#Iteration in 2D array
arr=np.arange(6).reshape(2,3)
for i in np.nditer(arr):
    print(i)
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in arr2:
    for y in x:
        print(y)

0
1
2
3
4
5
1
2
3
4
5
6
7
8
9
10


In [109]:
#Iteration in 3 D array
arr=np.arange(12).reshape(2,3,2)
print(arr)
for i in np.nditer(arr):
    print(i)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
0
1
2
3
4
5
6
7
8
9
10
11


In [117]:
#3 D Array
arr=np.array([[[1,2],[2,3],[4,5]],[[6,7],[8,9],[9,6]]])
print(arr)

for i in arr:
    for j in i:
        for k in j:
            print(k)

[[[1 2]
  [2 3]
  [4 5]]

 [[6 7]
  [8 9]
  [9 6]]]
1
2
2
3
4
5
6
7
8
9
9
6


In [124]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
for i in np.nditer(arr2[:,::2]):
    print(i)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
3
5
6
8
10


In [128]:
#Enumerate -------------returns key value pair (index--value)

arr2=np.array([1,2,3,4,5])
print(arr2)
for key,value in np.ndenumerate(arr2):
    print(key,value)

[1 2 3 4 5]
(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [132]:
arr=np.arange(6).reshape(3,2)
print(arr)
for key,value in np.ndenumerate(arr):
    print(key,value)

[[0 1]
 [2 3]
 [4 5]]
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5


In [133]:
#Joining Numpy arrays
# 1. concatenate() -------np.concatenate(arr1,arr2)
# 2. stack() -------------np.stack(arr1,arr2)

In [147]:
import numpy as np
def con_cat(*args):
    return np.concatenate(args)


arr1=np.arange(3)
arr2=np.arange(3)
result=con_cat(arr1,arr2)
print(result)


    

[0 1 2 0 1 2]


In [169]:
a1=np.array([[1,2,3],[4,5,6]])
print(a1)
a2=np.array([[11,12,13],[14,15,16]])
print(a2)
print(np.concatenate((a1,a2),axis=0))
print(np.concatenate((a1,a2),axis=1))

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [171]:
#stack() 
arr1=np.array([2,3,4])
arr2=np.arange(3)
print(arr1,arr2)
print(np.stack((arr1,arr2),axis=0))
print(np.stack((arr1,arr2),axis=1))

[2 3 4] [0 1 2]
[[2 3 4]
 [0 1 2]]
[[2 0]
 [3 1]
 [4 2]]


In [172]:
# hstack--- stacking along rows
# vstack--- stacking along columns
# dstack---- stacking along depth(height)


In [176]:
a1=[1,2,3]
a2=[4,5,6]
np.hstack((a1,a2))

array([1, 2, 3, 4, 5, 6])

In [177]:
np.vstack((a1,a2))

array([[1, 2, 3],
       [4, 5, 6]])

In [178]:
np.dstack((a1,a2))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [179]:
#splitting array
#  np.array_split(arr,no.of splits)

In [189]:
#1 D Array
arr=np.arange(10)
print(arr)
np.array_split(arr,5)
np.array_split(arr,4)
#np.array_split(arr,6)

[0 1 2 3 4 5 6 7 8 9]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9])]

In [196]:
# 2 D Array
a=np.arange(12).reshape(3,4)
print(a)
np.array_split(a,4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([], shape=(0, 4), dtype=int32)]

In [201]:

print(a)
np.hsplit(a,4)                     #along rows

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [8]:
arr=np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [10]:
arr[2:4,5:7]

array([[25, 26],
       [35, 36]])

In [205]:
#Searching in an array
# where() method
arr=np.array([[11,34,21,35],[45,34,66,12],[11,35,12,21]])
print(arr)
x=np.where(arr==21)
print(x)

[[11 34 21 35]
 [45 34 66 12]
 [11 35 12 21]]
(array([0, 2], dtype=int64), array([2, 3], dtype=int64))


In [209]:
arr=np.array([2,3,6,7,8])
np.where(arr%2==0)

(array([0, 2, 4], dtype=int64),)

In [211]:
arr=np.array([[11,34,21,35],[45,34,66,12]])
print(arr)
np.where(arr%2!=0)

[[11 34 21 35]
 [45 34 66 12]]


(array([0, 0, 0, 1], dtype=int64), array([0, 2, 3, 0], dtype=int64))

In [219]:
#searchsorted() ---------- performs binary search in array anf returns index where specified value would be inserted... used on sorted array
arr=np.array([6,7,8,9])
np.searchsorted(arr,7)       #default search starts from left
np.searchsorted(arr,10,side='right')

4

In [220]:
#multiple values
np.searchsorted(arr,[5,10])

array([0, 4], dtype=int64)

In [225]:
#sorting 1D array

arr=np.array([[11,34,21,35],[45,34,66,12]])
print(arr)
np.sort(arr)
arr1=np.array(['cherry','banana','apple'])
np.sort(arr1)
arr2=np.array([True,False,True,False])
np.sort(arr2)

[[11 34 21 35]
 [45 34 66 12]]


array([False, False,  True,  True])

In [278]:
# Filtering ---------creating new array from existing based on some condition
arr=[41,42,45,46]
filterd_arr=[]
for i in arr:
    if i>43:
        filterd_arr.append(True)
    else:
        filterd_arr.append(False)
print(filterd_arr)
arr[arr>41]

[False, False, True, True]


TypeError: '>' not supported between instances of 'list' and 'int'

In [248]:
arr=np.arange(1,20,2).reshape(5,2)
arr

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [250]:
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [253]:
arr=np.ones(5)
arr*5

array([5., 5., 5., 5., 5.])

In [258]:
arr=np.ones((4,5))
arr


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [260]:
arr=np.linspace(1,10,5)       # 5 evenly spaced values between 1 to 10
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [262]:
arr=np.eye(5)             # identity matrix
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
arr=np.random.rand(5)
print(arr)
arr1=np.random.rand(5,4)
print(arr1)
arr2=np.random.randint(5,10)
print(arr2)
arr2=np.random.randint(1,5,10)    # 10 int values
print(arr2)


[0.89958132 0.55894892 0.699335   0.42482261 0.55824394]
[[0.44602087 0.26629013 0.18655263 0.27765973]
 [0.86343473 0.91718637 0.66301615 0.46770445]
 [0.09647468 0.79855171 0.68739982 0.29533863]
 [0.59896578 0.29329972 0.69023671 0.37894505]
 [0.7004646  0.09523008 0.67071419 0.984039  ]]
8
[3 2 4 4 3 2 1 3 2 1]


In [276]:
arr=np.arange(20,35).reshape(3,5)
print(arr)
print(arr.max())
print(arr.min())
print(arr.argmax())
print(arr.argmin())

[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]]
34
20
14
0


In [285]:
arr1=np.array([5,6,7,8,9])
arr2=np.arange(5)
print(arr1,arr2)

[5 6 7 8 9] [0 1 2 3 4]


In [286]:
arr1+arr2

array([ 5,  7,  9, 11, 13])

In [287]:
arr1-arr2

array([5, 5, 5, 5, 5])

In [288]:
arr1*3

array([15, 18, 21, 24, 27])

In [289]:
arr1+100

array([105, 106, 107, 108, 109])

In [290]:
arr1**3

array([125, 216, 343, 512, 729], dtype=int32)

In [291]:
np.sqrt([25])

array([5.])

In [293]:
print(arr1)
np.exp(arr1)

[5 6 7 8 9]


array([ 148.4131591 ,  403.42879349, 1096.63315843, 2980.95798704,
       8103.08392758])

In [295]:
1/0

ZeroDivisionError: division by zero

In [26]:
a=np.array([[5,6,7],[8,9,10]])
print("Orogonal array is:",a)
flatten_a=a.flatten()
print("Flattened array is:",flatten_a)
ravel_a=a.ravel()
print("Ravel array is:",ravel_a)


#doesnt affect original array
flatten_a[0]=99
print("\nAfter changing in flatten","\n",a,"\n",flatten_a)


#affects original array
ravel_a[0]=1111
print("\nAfter changing in ravel","\n",a,"\n",ravel_a)

Orogonal array is: [[ 5  6  7]
 [ 8  9 10]]
Flattened array is: [ 5  6  7  8  9 10]
Ravel array is: [ 5  6  7  8  9 10]

After changing in flatten 
 [[ 5  6  7]
 [ 8  9 10]] 
 [99  6  7  8  9 10]

After changing in ravel 
 [[1111    6    7]
 [   8    9   10]] 
 [1111    6    7    8    9   10]


In [32]:
full_array=np.full(shape=(2,3),fill_value=5)
print(full_array)

[[5 5 5]
 [5 5 5]]


In [42]:
arr=np.arange(1,20,2).reshape(5,2)
print(arr)
np.where(arr==11)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


(array([2], dtype=int64), array([1], dtype=int64))

In [64]:
d={
    
    'key1':'sudh',
    234:[23,45,656]
}
print(list(d.keys())[0])


key1


In [67]:
arr=np.array([[1,2,3],[4,5,6]])
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [83]:
#You can add a new axis to an array using the expand_dims() method by providing the array and the axis along which to expand:
arr=np.array([1,2,3])
b=np.expand_dims(arr,axis=0)
c=np.expand_dims(arr,axis=1)
print(arr,b,c)

[1 2 3] [[1 2 3]] [[1]
 [2]
 [3]]


In [87]:
arr=np.array([[[1,2,3],[4,5,6]]])
print(arr)
np.squeeze(arr,axis=0)

[[[1 2 3]
  [4 5 6]]]


array([[1, 2, 3],
       [4, 5, 6]])