In [1]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 10B6-0DC8

 Directory of C:\Users\kanti\OneDrive\Desktop\ML

24/09/2022  07:09    <DIR>          .
23/09/2022  21:18    <DIR>          ..
24/09/2022  07:09    <DIR>          .ipynb_checkpoints
17/09/2022  07:08       140.600.832 city_temperature.csv
16/09/2022  08:06            92.108 Pandas -II.ipynb
17/09/2022  08:28           173.811 Pandas -III.ipynb
18/09/2022  08:46            73.594 Pandas -IV.ipynb
22/09/2022  07:48            15.587 Pandas sql.ipynb
19/09/2022  07:51            57.503 Pandas V.ipynb
22/09/2022  07:26            11.397 Pandas VI.ipynb
15/09/2022  08:20            85.184 Pandas.ipynb
22/09/2022  07:20                 0 te.txt
18/09/2022  08:18               273 test.csv
22/09/2022  07:38             1.011 test.html
15/09/2022  07:45                72 Untitled.ipynb
22/09/2022  07:04             3.137 Untitled1.ipynb
24/09/2022  07:09                72 Untitled2.ipynb
22/09/2022  07:22               134 weath

In [5]:
import pandas as pd


df = pd.read_csv('city_temperature.csv')

C:\Users\kanti\AppData\Local\Temp\ipykernel_4196\1326595078.py:4: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('city_temperature.csv')


In [9]:
df[2:3] #default

Region  Country State     City  Month  Day  Year  AvgTemperature
2  Africa  Algeria   NaN  Algiers      1    3  1995            48.8

In [11]:
df.set_index('City',inplace=True)

In [18]:
df.loc['Algiers':'San Juan Puerto Rico',:]

Region  Country                   State  Month  \
City                                                                          
Algiers                      Africa  Algeria                     NaN      1   
Algiers                      Africa  Algeria                     NaN      1   
Algiers                      Africa  Algeria                     NaN      1   
Algiers                      Africa  Algeria                     NaN      1   
Algiers                      Africa  Algeria                     NaN      1   
...                             ...      ...                     ...    ...   
San Juan Puerto Rico  North America       US  Additional Territories      7   
San Juan Puerto Rico  North America       US  Additional Territories      7   
San Juan Puerto Rico  North America       US  Additional Territories      7   
San Juan Puerto Rico  North America       US  Additional Territories      7   
San Juan Puerto Rico  North America       US  Additional Territories      7   

                      Day  Year  AvgTemperature  
City                                             
Algiers                 1  1995            64.2  
Algiers                 2  1995            49.4  
Algiers                 3  1995            48.8  
Algiers                 4  1995            46.4  
Algiers                 5  1995            47.9  
...                   ...   ...             ...  
San Juan Puerto Rico   27  2013            82.4  
San Juan Puerto Rico   28  2013            81.6  
San Juan Puerto Rico   29  2013            84.2  
San Juan Puerto Rico   30  2013            83.8  
San Juan Puerto Rico   31  2013            83.6  

[2906327 rows x 7 columns]

In [ ]:
numerical Python

In [ ]:
it is use to perform complex math cal

In [ ]:
list,tuple,set

numpy ?

In [ ]:
numpy is faster that list,tuple  built on c

numpy use to perform cal on n-dim


relation algebra cal using numpy

In [ ]:
!pip install numpy

In [19]:
import numpy as np

In [27]:
a = np.array([23,64,786,34,863,])

In [28]:
type(a)

numpy.ndarray

In [29]:
a.ndim

1

In [30]:
a

array([ 23,  64, 786,  34, 863])

In [33]:
a[1:4]

array([ 64, 786,  34])

In [74]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a.ndim

2

In [40]:
a = np.array(['54','534','24'],dtype=int)

In [41]:
a

array([ 54, 534,  24])

In [60]:
a = np.array([1,2,3],dtype = 'int8')

In [61]:
a

array([1, 2, 3], dtype=int8)

In [62]:
a.size

3

In [63]:
a.itemsize*a.size

3

In [64]:
import sys

In [65]:
p = [1,2,3]  #PVM

In [78]:
sys.getsizeof(p)

120

In [71]:
p1 = np.array([1,2,3],dtype='int8')

In [72]:
p1.itemsize*p1.size

3

In [73]:
a

array([1, 2, 3], dtype=int8)

In [75]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a.shape

(3, 3)

In [80]:
3*3

9

In [ ]:
1,9
9,1
3,3


In [82]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [83]:
a.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [157]:
a = np.array([[1,2,3],[4,5,6]])

In [86]:
a.shape

(2, 3)

In [87]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
2*3

3,2
1,6
6,1

In [88]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
a = a.reshape(6,1)

In [91]:
a.ndim

2

In [92]:
a

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [112]:
arr1 = np.array([[[2,17], [45,90]], [[88, 92], [60, 76]],[[76,33],[20,18]]])

In [113]:
arr1.ndim

3

In [114]:
arr1

array([[[ 2, 17],
        [45, 90]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [115]:
arr1.shape

(3, 2, 2)

In [ ]:
range() --> generation of int number

In [118]:
a = np.arange(1,15,3)

In [119]:
a

array([ 1,  4,  7, 10, 13])

In [120]:
a = np.empty([3,4],dtype=int)

In [121]:
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [155]:
a = np.empty([4,4],dtype=int)

In [156]:
a

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 7012444, 7209057],
       [6881396, 4259932, 7340144, 6357060],
       [6357108, 4980828, 6488175, 7077985]])

In [141]:
a = np.zeros([4,4])

In [142]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [143]:
a = np.ones([4,4])

In [144]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [158]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
a[0,:]

array([1, 2, 3])

In [161]:
a[:,1:]

array([[2, 3],
       [5, 6]])

In [162]:
a[1:,2]

array([6])

In [163]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
b = np.array([[7,94,45],[55,57,34]])

In [165]:
b

array([[ 7, 94, 45],
       [55, 57, 34]])

In [166]:
a+b

array([[ 8, 96, 48],
       [59, 62, 40]])

In [167]:
a*b

array([[  7, 188, 135],
       [220, 285, 204]])

In [169]:
a = np.array([[1,2,3],[4,5,6]])

In [170]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
b = np.array([[1,2,3],[4,5,6]])

In [172]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [173]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [174]:
a*7

array([[ 7, 14, 21],
       [28, 35, 42]])

In [175]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [176]:
a = np.array([[1,2,3],[4,5,6]])

In [184]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [181]:
b = np.array([[4,6,12],[7,8,34],[9,6,90]])

In [182]:
b

array([[ 4,  6, 12],
       [ 7,  8, 34],
       [ 9,  6, 90]])

In [183]:
np.dot(a,b)

array([[ 45,  40, 350],
       [105, 100, 758]])

In [185]:
1*4+2*7+3*9

45

In [186]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [188]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [189]:
b

array([[ 4,  6, 12],
       [ 7,  8, 34],
       [ 9,  6, 90]])

In [191]:
b.flatten()

array([ 4,  6, 12,  7,  8, 34,  9,  6, 90])

In [194]:
np.random.randint(0,10,(3,3))

array([[7, 1, 0],
       [7, 6, 6],
       [0, 8, 0]])

In [200]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [196]:
#where --> index return condition --True

In [198]:
a = np.array([1,9,5,3,8,9,3])

In [199]:
np.where(a>5)

(array([1, 4, 5], dtype=int64),)

In [201]:
a

array([1, 9, 5, 3, 8, 9, 3])

In [202]:
np.min(a)

1

In [203]:
np.max(a)

9

In [204]:
np.sum(a)

38

In [ ]:
application 

matplotlib,seaborn

EDA -->
stats --> min,max,sum,mean,median,mode ,std,pearsonl correlation